### ISSUE TITLE
i cant even explain this...

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [appu1232/Selfbot-for-Discord#6]
Whenever i run the loopself.py it just brings up a screenshotting crosshair and makes picture files called whatever it tried to import, importing works fine on its own

**Comment by appu1232** [comment]
Uh...I have no idea what's causing that but if you are on windows you should be fine running it with ``run.bat``

**Comment by gidoBOSSftw5731** [comment]
ubuntu

**Comment by appu1232** [comment]
I'm gonna need more info with screenshots if possible. You were able to run the bot fine earlier right? I'm not sure what could be causing the problem.

**Comment by gidoBOSSftw5731** [comment]
yeah, i really dont know... i did reinstall pretty table and spice api, lets try removing them...

**Comment by gidoBOSSftw5731** [comment]
Nope...

**Comment by appu1232** [comment]
I'm going to need some screenshots and also how exactly you are running the bot. I can't really replicate your problem and without some context I can't really help.

**Comment by gidoBOSSftw5731** [comment]
im running the bot exactly how it says, if i comment all the imports it doesnt do it, but we kinda need imports, just rebooted, gonna try again

**Comment by gidoBOSSftw5731** [comment]
nope... 
![screenshot from 2017-03-22 22-21-21](https://cloud.githubusercontent.com/assets/13257145/24229044/eecd355a-0f4d-11e7-87a1-c8c73f8e92ca.png) gnight for now, its late...

**Comment by gidoBOSSftw5731** [comment]
Im gonna close this, i installed spice_api and prettytable through easy_install and it worked...
